### ISSUE TITLE
[董天成]移动端React与SPA的首屏优化

### ISSUE THREAD

**Issue by wssgcg1213** [wssgcg1213/feu#2]
# 移动端React与SPA的首屏优化

-- 百度FEX 董天成
### 序

```
...前面省略一万条聊天记录
董天成  00:21:11
我马上就要上线一个项目。。
董天成  00:21:18
手百入口导流
董天成  00:21:29
预测千万。
AP-DeadSoul  00:21:35
66666
董天成  00:21:35
我已经优化到首屏600ms
FRP-Boolean93  00:21:42
Pots
Ling。  00:21:43
你们千万级的后端是靠什么支撑的
FRP-Boolean93  00:21:46
Orz 
AP-DeadSoul  00:21:46
不愧是第三步的程序员
董天成  00:21:49
 php
FRP-Boolean93  00:22:02
快说说具体的
```
### 正文

`因为是聊天内容截取, 所以可能比较乱, 请自己汲取营养吧. 引用内的为非老董同学说的话.`

> FRP-Boolean93  00:22:10
> 
> 用了些啥
> 
> 计算机-Peter  00:22:25
> 
> 围观华山论剑

也没用啥高级技术。

> FRP-Boolean93  00:22:28
> 
> 腾讯的朋友网也是php撑起来的

用了些技巧

快速出首屏的技巧就是把最容易出来的先出来

虽然整个页面用 React 写的。。

不过出首屏的时候 React 还没下载好

> Ling。  00:23:26
> 
>  600ms 是图片为主的还是什么的页面

一个图片和2行字

等正式上线再给个真实数据吧。 测试机不准

不过流程是这样的。

测试机平均相应>500ms

我这个都是实际时间 - 500ms 得到的

现在的环境是 PHP+ React

因为占用首屏有两大因素。

忘说前提了。

对于是 spa 应用， 占用首屏的2大因素

出首屏会在 js 加载之后才有。

因为 html 刚下载下来的时候， 页面是这样的

整个 body 全是空的

通过下载 js，然后用浏览器渲染出页面就很占时间。

假如后端接口返回又很慢的话

比如一个接口跑了1.44s。。- -

那出页面 = 下载 html + 下载 css和 js + 发送异步请求 + 服务器返回 + 出页面

假如换个思路

因为出首屏是没有必要干那么多事情的。

一般页面的最上面也就是 title， 头图， 一个简单板块

所以满足要什么给什么原则就行了

那就进行拆分

先是拆 UI。 

在 UI层优化

对于后端提供的服务， 可以采用并行发请求的方式。。

而不是串行调接口。

这样能节省30% - 40%的UI 返回的时间

可能之前调取服务的方式是  a -> b -> c -> d

(现在是)    

```
a ->  | -> b  -> response
      | -> c  
      | -> d
```

当然如果有 Node 的话， 优化就更大了 //略一万字

有时很原始的方式还是最高效的方式。

![1](https://cloud.githubusercontent.com/assets/3922719/12332142/da57afa4-bb27-11e5-9e3e-30e4adb2e034.jpg)
(图1)

我写了2个原生 ajax 请求在 html 的最顶部。

让 xhr 和加载 js 并行加载

用加载 js 的时间来中和服务器跑数据用的时间

优先发送异步请求。

这2个请求都很耗时。 直接在返回 html 之前就处理的话，非常影响首屏。

所以采用异步接口， 然后只要 html 一返回。就优先加载

看到我那个 window.initBest 没？

这可是很有魔性的代码

![2](https://cloud.githubusercontent.com/assets/3922719/12332160/f42464ae-bb27-11e5-8bbc-230002a730d5.jpg)
(图2)

再看 react 这里

render 是 react-dom的 render

对于提前发送的异步请求。 通过注册2个函数的方式， 就可以只要 react 一加载好， 直接出页面， 根本不用任何等待。

我在 html 里面放了2个 react 渲染的入口

![3](https://cloud.githubusercontent.com/assets/3922719/12332167/f9b48516-bb27-11e5-99f7-862768c63ed5.jpg)
(图3)

我计算了一下。

![4](https://cloud.githubusercontent.com/assets/3922719/12332170/ffc328e0-bb27-11e5-954a-226c7c91e0c5.jpg)

(图4)

下面的请求比上面的快。

因为下面的请求是页面中部的内容。

所以就提前渲染好了。

没必要再等待其他的了

![5](https://cloud.githubusercontent.com/assets/3922719/12332173/043720fc-bb28-11e5-9c7d-c4bc39a6e7e1.jpg)

(图5)

2就是页面中部

1是首屏出来的时候

忘记说了。

1那块是直接用 PHP 渲染出来的。

最快

数据直接用 PHP 打在html 里面。

虽然看着有点原始， 却是最快速的方案
### Q&A
- Q1. 既然静态资源加载是阻塞首屏渲染的第一元凶, 有没有针对性处理的方法, 因为很大一部分库/框架代码/CSS是对首屏没什么卵用的
- A1.  针对性处理就是。 既然采用模块化开发。 那就把首屏所需要的模块单独处理。有时很原始的方式还是最高效的方式。比如。。(图6)
  ![6](https://cloud.githubusercontent.com/assets/3922719/12332182/095466a8-bb28-11e5-8399-18563fc9a06e.jpg)
- Q2. 模板里没有兜底数据吗 假如api挂了会有策略吗
- A2. API 挂了就索性不显示模块。。这个没办法的事情
- Q3. 缓存策略?
- A3. 其实缓存并不能为首屏提高多少优化的空间， 毕竟缓存都是缓存图片。 最多出首屏的时候，图片字体图标更快出来。 其他资源最好不缓存。 
  
  ​
- Q4. 针对图片有没有更多的姿势
- A4. 图片的优化策略就是， 给图片固定容器，多用 background 那一大堆。 减少页面重排。这样图片即使挂了， 页面也正常。
- Q5. css挂了怎么解决
- A5. css 挂了。。就跟兴妈说头掉了怎么办一样 cdn 做 dns 优化的, 负载均衡到各台静态服务器。 挂的概率非常低, 真的挂了。。发邮件找 OP 吧。(OP: 是的，挂的几率很低，假设五套系统一套挂了其余负载才百分之25，基本不会再挂，运维还有noah监控，故障都是秒级切换)
### 后记

今晚的分享学习了很多，感谢董天成  
... 欢迎大家在群里讨论各类前端问题. 有任何建议意见请联系管理员(づ￣ 3￣)づ

**Comment by andycall** [comment]
我觉得有必要再整理一下。

**Comment by xxxsf** [comment]
好好整理~
